trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  - group: workshop-common
  - group: workshop-prod
  - name: buildConfiguration
    value: Release

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: BuildValidatePackage
    displayName: Build, validate, and package
    jobs:
      - job: ci
        displayName: CI
        steps:
          - checkout: self
            clean: true

          - template: pipelines/templates/dotnet-build.yml

          - script: |
              set -euo pipefail
              helm lint helm/workshop-app --values helm/workshop-app/values.yaml --values helm/workshop-app/values-prod.yaml
            displayName: Lint Helm chart

          - template: pipelines/templates/docker-build-push.yml
            parameters:
              imageRepository: workshop-api
              dockerfile: Nlb.Workshop.Api/Dockerfile
              versionTag: $(ReadProjectVersion.version)

          - template: pipelines/templates/docker-build-push.yml
            parameters:
              imageRepository: workshop-consumer
              dockerfile: Nlb.Workshop.Consumer.Worker/Dockerfile
              versionTag: $(ReadProjectVersion.version)

  - stage: ValuesUpdate
    displayName: "Update value file for chart"
    dependsOn: BuildValidatePackage
    condition: succeeded()
    variables:
      - name: ImageTag
        value: $[ stageDependencies.BuildValidatePackage.ci.outputs['ReadProjectVersion.version'] ]
    jobs:
      - template: pipelines/templates/values-update.yml
        parameters:
          imageTag: $(ImageTag)
