trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: CI
      trigger:
        branches:
          include:
            - main

variables:
  - group: workshop-common
  - group: workshop-prod

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Deploy
    displayName: "Deploy chart to AKS cluster"
    jobs:
      - job: cd
        displayName: CD
        steps:
          - checkout: self
            clean: true

          - template: pipelines/templates/deploy-helm.yml
            parameters:
              environmentName: prod

  - stage: Versioning
    displayName: "Update project version"
    dependsOn: Deploy
    condition: succeeded()
    jobs:
      - template: pipelines/templates/auto-versioning.yml
