apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workshop-app.fullname" . }}-config
  labels:
    {{- include "workshop-app.labels" . | nindent 4 }}
data:
  Messaging__Provider: {{ .Values.config.messagingProvider | quote }}
  Messaging__Serialization__DefaultFormat: {{ .Values.config.defaultPayloadFormat | quote }}
  Messaging__EventHubs__EventHubName: {{ .Values.config.eventHubName | quote }}
  Messaging__EventHubs__ConsumerGroup: {{ .Values.config.consumerGroup | quote }}
  Messaging__EventHubs__ReplayConsumerGroup: {{ .Values.config.replayConsumerGroup | quote }}
  Messaging__EventHubs__CheckpointContainerName: {{ .Values.config.checkpointContainerName | quote }}
  Messaging__Kafka__Topic: {{ .Values.config.eventHubName | quote }}
  Messaging__Kafka__ConsumerGroup: {{ .Values.config.consumerGroup | quote }}
  Messaging__Kafka__ReplayConsumerGroup: {{ .Values.config.replayConsumerGroup | quote }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  DOTNET_ENVIRONMENT: {{ .Values.config.dotnetEnvironment | quote }}
